### ISSUE TITLE
Not working today

### ISSUE THREAD

**Issue by suggested-username** [drknzz/auto-lingo#6]
Today I run it, but the chrome just disappeared without giving any error messages. Tried on Windows 10 and BigSur 11.5.2<br><br>
<img src="https://ashenray.de/23.44.26.png"></img>

**Comment by PvPsFinest** [comment]
Some things on the website were updated breaking some things. I got it working pretty good with simple fixes for Japanese Stories on my fork if you want to try it. I'm working on updating learn, but it is pretty janky.
https://github.com/PvPsFinest/auto-lingo/tree/patch-1

**Comment by suggested-username** [comment]
Your new patch solves it. Thank you very much
