### ISSUE TITLE
How to i make the script go into learn automatically?

### ISSUE THREAD

**Issue by mykuh** [drknzz/auto-lingo#9]
hello! the script is working fine so far but i cant seem to figure out how i can do the learn lessons automatically. it only goes to stories. please reach back very soon.

**Comment by PvPsFinest** [comment]
If you want to do lessons and not stories:
The "-l" flag. I.E.
py auto-lingo.py -l
Warning learn wasn't working when I used it on Japanese

If you want it to do stories elaborate.
